/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class VOIDescription {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VOIDescription(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VOIDescription obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_VOIDescription(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCenter(double value) {
    imebraJNI.VOIDescription_center_set(swigCPtr, this, value);
  }

  public double getCenter() {
    return imebraJNI.VOIDescription_center_get(swigCPtr, this);
  }

  public void setWidth(double value) {
    imebraJNI.VOIDescription_width_set(swigCPtr, this, value);
  }

  public double getWidth() {
    return imebraJNI.VOIDescription_width_get(swigCPtr, this);
  }

  public void setDescription(SWIGTYPE_p_std__wstring value) {
    imebraJNI.VOIDescription_description_set(swigCPtr, this, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring getDescription() {
    return new SWIGTYPE_p_std__wstring(imebraJNI.VOIDescription_description_get(swigCPtr, this), true);
  }

  public VOIDescription() {
    this(imebraJNI.new_VOIDescription(), true);
  }

}
